name: raiser_annotation
description: Annotations for the Raiser domain event library code generator.
version: 1.0.0
repository: https://github.com/zooper/raiser
issue_tracker: https://github.com/zooper/raiser/issues

environment:
  sdk: ^3.10.4

resolution: workspace

topics:
  - events
  - annotations
  - code-generation

dev_dependencies:
  test: ^1.25.6
