name: raiser_example
description: Example usage of the Raiser package
publish_to: none

environment:
  sdk: ^3.10.4

dependencies:

  zooper_flutter_core: ^1.0.2

  raiser:
    path: ../
  raiser_annotation:
    path: ../../raiser_annotation

dev_dependencies:
  lints: ^6.0.0
  build_runner: ^2.4.0
  raiser_generator:
    path: ../../raiser_generator

